[project]
name = "chinlit-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
chinlit-chatbot = "chinlit_chatbot:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
